[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
license = "MIT"
edition = "2024"

[workspace.lints.rust]
rust_2018_idioms = "warn"
unused_lifetimes = "warn"
unreachable_pub = "warn"
deprecated_in_future = "warn"

[workspace.lints.clippy]
multiple_crate_versions = "allow"

[workspace.dependencies]
# TODO: change dep on a real one
simplicityhl = { git = "https://github.com/ikripaka/SimplicityHL.git", branch = "feat/fmt-parser", features = ["fmt"] }
serde = { version = "1.0.228" }
serde_json = { version = "1.0.150" }
thiserror = { version = "2.0.18" }
either = { version = "1.16.0" }
prettysimf = { path = "./crates/prettysimf" }
term = { version = "1.2.1" }

