[package]
name = "prettysimf"
version = "0.0.1"
license.workspace = true
edition.workspace = true
description = "Simplicityhl prettier library"
readme = "README.md"

[lints]
workspace = true

[dependencies]
simplicityhl = { workspace = true }

annotate-snippets = { workspace = true }
either = { workspace = true }
pretty = { workspace = true }
serde = { workspace = true }
similar = { workspace = true }
term = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }
