[package]
name = "simfmt"
version = "0.0.1"
description = "Formatting tool for SimplicityHL"
repository = "https://github.com/ikripaka/simplefmt"
readme = "../README.md"
license.workspace = true
edition.workspace = true

[[bin]]
name = "simfmt"
path = "src/bin/main.rs"

[lints]
workspace = true

[dependencies]
anyhow = { version = "1.0.103" }
annotate-snippets = { version = "0.12.16" }
pretty = { version = "0.12.5" }
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
getopt = { version = "1.1.9" }
itertools = { version = "0.15.0" }
globwalk = { version = "0.9.1" }
similar = { version = "3.1.1" }
getopts = { version = "0.2.24" }
toml = { version = "0.9.8" }

simplicityhl = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
either = { workspace = true }
prettysimf = { workspace = true }
term = { workspace = true }

